### ISSUE TITLE
Обращение к БД 

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_Failless#2]
https://github.com/go-park-mail-ru/2020_1_Failless/blob/1486a3c688a998d0df89344d516d9dcacc59765c/db/user.go#L8

Вы в каждую функцию кидаете первым аргументов пул потоков. Но разумнее создать отдельную структуру 
`
type UserRepository struct {
        db *pgx.ConnPool
}
`
Все функции из того пакета сделать методами этой структуры и вуаля. Вам больше не надо кидать одну и ту же переменную в каждую функцию. Ее надо предоставить только конструктору структуры. 

P.S. `db *pgx.ConnPool` указатель. Если на вход придет nil, то будет паника. Лучше поставить одну проверку в конструкторе, чем n проверок для n функций, верно?)

**Comment by rowbotman** [comment]
Already fixed
